# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Regexp-Parser
version:      0.20
version_from: lib/Regexp/Parser.pm
installdirs:  site
requires:
    NEXT:                          

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
