name: Perl6-Pugs
version: 6.2.13
abstract: A Perl 6 Implementation
author: Audrey Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
build_requires:
no_index:
  directory:
    - debian
    - docs/Perl6
    - docs/summaries
    - docs/AES
    - docs/notes
    - docs/other
    - examples
    - ext
    - inc
    - misc
    - perl5
    - script
    - src
    - util
    - dist
generated_by: Module::Install version 0.36
