name: Perl6-Pugs
version: 6.2.0
abstract: A Perl 6 Implementation
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
build_requires:
no_index:
  directory:
    - inc
    - modules
    - ext
    - script
    - util
generated_by: Module::Install version 0.36
