name: Perl6-Pugs
version: 6.0.9
abstract: A Perl6 Implementation
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
no_index:
  directory:
    - inc
    - modules
generated_by: Module::Install version 0.36
