name: Perl6-Pugs
version: 6.2.8
abstract: A Perl 6 Implementation
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
build_requires:
no_index:
  directory:
    - debian
    - docs
    - examples
    - ext
    - inc
    - modules
    - perl5
    - script
    - src
    - util
generated_by: Module::Install version 0.36
